version: '3'
services:
  eureka-server:
      image: ugurciftci/service-registry:latest
      ports:
        - "8761:8761"
  config-server:
      image: ugurciftci/wallet-config-server:latest
      ports:
        - "4000:4000"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge