server:
  port: 4000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/uurdev/order-app-config.git
          clone-on-start: true
    consul:
      discovery:
        instance-id: config-server
        serviceName: myprefix-${spring.application.name}
